"""Segunda Migracion

Revision ID: 48f93db644cc
Revises: a377bd189c8b
Create Date: 2026-03-13 09:33:37.022984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48f93db644cc'
down_revision = 'a377bd189c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('apa',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('ama',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.alter_column('ama',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('apa',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nom',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
