"""Permitir maestro_id nulo en cursos e inscripciones

Revision ID: 97d8d253a03e
Revises: 4840b4903c37
Create Date: 2026-04-17 09:59:34.173328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97d8d253a03e'
down_revision = '4840b4903c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.alter_column('maestro_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.alter_column('maestro_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.alter_column('maestro_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.alter_column('maestro_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
